[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_SKIP
	-D LV_COLOR_DEPTH=16
	-D LV_TICK_CUSTOM=1
	-D LV_USE_LOG=1
	-D LV_USE_METER=1
	-D LV_USE_CANVAS=1
	-D LV_FONT_MONTSERRAT_32=1
	-D LV_FONT_MONTSERRAT_40=1
	-D CORE_DEBUG_LEVEL=3

board_build.arduino.memory_type = qio_opi

upload_protocol = esptool
upload_flags = 
	--no-stub
monitor_rts = 0
monitor_dtr = 0

lib_deps = 
	moononournation/GFX Library for Arduino@^1.4.0
	lvgl/lvgl@^8.3.9
	bblanchon/ArduinoJson@^7.0.0
